version: '3.8'

services:
  redis-m1:
    image: redis:latest
    container_name: redis-m1
    ports:
      - "6379:6379"
    command: redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
      --requirepass ecsimsw 
      --masterauth ecsimsw
    volumes:
      - ~/data/redis-data-m1:/data
    restart: always

  redis-sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    ports:
      - "26379:26379"
    command: redis-sentinel /etc/sentinel/sentinel.conf
    volumes:
      - ./sentinel-m1.conf:/etc/sentinel/sentinel.conf
    depends_on:
      - redis-m1
    restart: always
