version: '3.8'

services:
  redis-s1:
    image: redis:latest
    container_name: redis-s1
    ports:
      - "6379:6379"
    command: redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
      --requirepass ecsimsw  
      --masterauth ecsimsw   
      --slaveof 192.168.1.101 6379
    volumes:
      - ~/data/redis-data-s1:/data
    restart: always

  redis-sentinel2:
    image: redis:latest
    container_name: redis-sentinel2
    ports:
      - "26379:26379"
    command:
      --redis-sentinel
      --/etc/sentinel/sentinel.conf
    volumes:
      - ./sentinel-s1.conf:/etc/sentinel/sentinel.conf
    depends_on:
      - redis-s1
    restart: always
